export const config = {
  pinningService: {
        name: 'pinata',
        endpoint: 'https://api.pinata.cloud/psa',
        key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIwYzk3ZjI5My1jMGFmLTQ3MzItOWQ2NS1lNTAyYTkzNDcwYzAiLCJlbWFpbCI6ImF4b2xvdGRldmVsb3BtZW50QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImlkIjoiRlJBMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfSx7ImlkIjoiTllDMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiI4ODEzMWNmMjdiYWU3MjkwOTAyZCIsInNjb3BlZEtleVNlY3JldCI6IjdiNWNlMjExYjZmNjU5MmQ0NWM0ODYxZjkyYWJmODhkZWUzNmFiOGMzMGJiMmQ4MmRjNWNlNWQ4ZDY3YWM2NjMiLCJpYXQiOjE2NjgyNzUyNjR9.alPUmIqltKbq9e3oDY5rtPwGMWMIIL97-MMHHKshHok'
    }
}
